implemented create and auth user, create and get order
bonus2k/go-musthave-diploma-tpl pull request #1
Opened 2023-11-09 09:23 UTC by bonus2k

2023-11-10 14:25 UTC, kilchik commented on cmd/gophermart/internal/models.go
> +type Value string
OrderStatus

2023-11-10 14:25 UTC, kilchik commented on cmd/gophermart/internal/models.go
> +	NEW        Value = "NEW"
OrderStatusNew Value = "NEW"

2023-11-15 19:44 UTC, bonus2k commented
TODO I will need add tests and write readme

2023-11-15 20:55 UTC, kilchik requested changes

2023-11-15 20:55 UTC, kilchik commented on cmd/gophermart/internal/migrations/sql/3_create_table_withdrawals.up.sql
> +    sum FLOAT,
Обсуждали, что либо BIGINT либо DECIMAL

2023-11-15 20:55 UTC, kilchik commented on go.sum
> +github.com/Azure/go-ansiterm v0.0.0-20230124172434-306776ec8161 h1:L/gRVlceqvL25UVaW/CKtUDjefjrs0SPonmDGUVOYP0=
Хорошо бы добавить README и Makefile

2023-11-15 20:55 UTC, kilchik commented on cmd/gophermart/main.go
> +	ticker := time.NewTicker(5 * time.Second)
Вынести константы в константы или в конфиг

2023-11-15 20:55 UTC, kilchik commented on cmd/gophermart/internal/repositories/storage.go
> +	err := store.db.GetContext(timeout,
Так нельзя. За время между Select и Insert может добавиться заказ другим запросом, поэтому тут нужна проверка через уникальный ключ

2023-11-15 20:55 UTC, kilchik commented on cmd/gophermart/internal/repositories/storage.go
> +	timeout, cancelFunc := context.WithTimeout(ctx, time.Second*5)
Обсуждали, что можно не добавлять отдельный таймаут, иначе 5 секунд нужно вынести в конфиг/константу

2023-11-15 20:55 UTC, kilchik commented on internal/interfaces/clients/accrual.go
> +	if strings.Contains(response.Status(), http.StatusText(http.StatusTooManyRequests)) {
При возможности сравнить числа всегда лучше сравнивать числа, а именно status code - это в разы быстрее

2023-11-15 20:55 UTC, kilchik commented on internal/logger.go
> +func NewLogger(level string) error {
Лучше назвать Init, от New интуитивно ожидаем возвращения созданного объекта

2023-11-15 20:55 UTC, kilchik commented on internal/migrations/migration.go
> +		panic(err)
Паник в чистом виде быть не должно - ошибку прокидываем наверх, там обрабатываем, если надо завершаем приложение

2023-11-15 20:55 UTC, kilchik commented on internal/migrations/sql/2_create_table_orders.up.sql
> +    accrual FLOAT,
BIGINT/DECIMAL

2023-11-16 09:30 UTC, bonus2k commented on cmd/gophermart/main.go
> +	ticker := time.NewTicker(5 * time.Second)
fix

2023-11-16 09:30 UTC, bonus2k commented on cmd/gophermart/internal/repositories/storage.go
> +	timeout, cancelFunc := context.WithTimeout(ctx, time.Second*5)
fix

2023-11-29 20:11 UTC, kilchik approved these changes

2023-11-29 20:11 UTC, kilchik commented on internal/services/pool_worker.go
> +	pause := make(chan struct{})
Лучше создавать этот канал до вызова worker и передать через аргумент - так будет более прозрачен скоуп жизни канала. В остальном решение выглядит хорошо

2023-11-29 20:11 UTC, kilchik commented on internal/utils/error.go
> +package utils
utils, misc и т д - муветон, со временем такие пакеты разрастаются семантически разнородными функциями и константами - сложно становится поддерживать. Если здесь все про ошибки, можно назвать errors

2023-11-29 20:11 UTC, kilchik commented on internal/utils/password.go
> +func SignPassword(password string) (string, error) {
Такое точно нельзя оставлять в utils :) Это может быть отдельный пакет auth, например

2023-11-29 20:11 UTC, kilchik commented on internal/services/user_services.go
> +var ErrIllegalUserArgument = errors.New("illegal user argument")
Я бы вынес в отдельный файл errors.go

2023-11-29 20:11 UTC, kilchik commented on internal/interfaces/handlers/user_api.go
> +func readSigned(r *http.Request, secretKey []byte) (string, error) {
Это лучше вынести в мидлварь

2023-11-30 09:24 UTC, merged